service: registrar-huevos

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
  # Permisos IAM para la Lambda
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt HuevosTable.Arn

# Para desarrollo local
plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true

functions:
  registrarHuevos:
    handler: handlers/handler.lambdaHandler
    events:
      - http:
          path: huevos
          method: post
          cors: true

resources:
  Resources:
    HuevosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Huevos-${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
