AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Lomas Altas - API para gestión de huevos

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: nodejs16.x
    Architectures:
      - x86_64

Resources:
  RegistrarHuevos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Environment:
        Variables:
          BOXES_TABLE_NAME: !Ref BoxesTable
          PALLETS_TABLE: !Ref PalletsTable
          ISSUES_TABLE: !Ref IssuesTable
          SYSTEM_CONFIG_TABLE: !Ref SystemConfigTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BoxesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PalletsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref IssuesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SystemConfigTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  BoxesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Boxes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: codigo
          AttributeType: S
        - AttributeName: ubicacion
          AttributeType: S
      KeySchema:
        - AttributeName: codigo
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ubicacion-index
          KeySchema:
            - AttributeName: ubicacion
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  PalletsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Pallets
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: codigo
          AttributeType: S
      KeySchema:
        - AttributeName: codigo
          KeyType: HASH

  IssuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Issues
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: IssueNumber
          AttributeType: S
      KeySchema:
        - AttributeName: IssueNumber
          KeyType: HASH

  SystemConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SystemConfig
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH

Outputs:
  HuevosFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HuevosFunction.Arn
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/" 