name: Deploy to Dev Lambda

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::515966525583:role/LambdaLomasAltas
          aws-region: us-east-2

      - name: Install dependencies
        run: npm install

      - name: Set environment variable for dev
        run: echo "STAGE=dev" >> $GITHUB_ENV

      - name: Create .env file for dev environment
        run: |
          echo "# Archivo de entorno generado automáticamente por GitHub Actions" > .env
          echo "# Despliegue de rama dev a lambda-dev" >> .env
          echo "# Fecha de generación: $(date)" >> .env
          echo "" >> .env
          echo "STAGE=dev" >> .env
          echo "NODE_ENV=development" >> .env
          echo "ENV_SOURCE=github_actions" >> .env
          echo "DEPLOYMENT_BRANCH=dev" >> .env
          echo "DEPLOYMENT_TIMESTAMP=$(date +%s)" >> .env
          
          echo "Contenido del archivo .env:"
          cat .env

      - name: Zip application
        run: |
          zip -r lambda.zip .

      - name: Deploy to Dev Lambda
        run: |
          aws lambda update-function-code \
            --function-name RegistrarHuevos-dev \
            --zip-file fileb://lambda.zip

      - name: Wait for Lambda update to finish
        run: |
          aws lambda wait function-updated \
          --function-name RegistrarHuevos-dev
          
      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name RegistrarHuevos-dev \
            --environment "Variables={STAGE=dev,NODE_ENV=development,DEPLOYMENT_BRANCH=dev,DEPLOYMENT_TIMESTAMP=$(date +%s)}" 