name: Deploy to Dev Lambda

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::515966525583:role/LambdaLomasAltas
          aws-region: us-east-2

      - name: Install dependencies
        run: npm install

      - name: Set environment variable for dev
        run: echo "STAGE=dev" >> $GITHUB_ENV

      - name: Zip application
        run: |
          zip -r lambda.zip .

      - name: Deploy to Dev Lambda
        run: |
          aws lambda update-function-code \
            --function-name RegistrarHuevos-dev \
            --zip-file fileb://lambda.zip 