name: Deploy to Lambda

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::515966525583:role/LambdaLomasAltas
          aws-region: us-east-2

      - name: Install deps and zip
        run: |
          npm install
          zip -r lambda.zip .

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name RegistrarHuevos \
            --zip-file fileb://lambda.zip
