name: Deploy to Production Lambda

on:
  push:
    branches: [master, main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::515966525583:role/LambdaLomasAltas
          aws-region: us-east-2

      - name: Install dependencies
        run: npm install

      - name: Set environment variable for production
        run: echo "STAGE=main" >> $GITHUB_ENV
          
      - name: Create .env file for production environment
        run: |
          echo "# Archivo de entorno generado automáticamente por GitHub Actions" > .env
          echo "# Despliegue de rama main/master a lambda de producción" >> .env
          echo "# Fecha de generación: $(date)" >> .env
          echo "" >> .env
          echo "STAGE=main" >> .env
          echo "NODE_ENV=production" >> .env
          echo "ENV_SOURCE=github_actions" >> .env
          echo "DEPLOYMENT_BRANCH=${GITHUB_REF##*/}" >> .env
          echo "DEPLOYMENT_TIMESTAMP=$(date +%s)" >> .env
          
          echo "Contenido del archivo .env:"
          cat .env

      - name: Zip application
        run: |
          zip -r lambda.zip .

      - name: Deploy to Production Lambda
        run: |
          aws lambda update-function-code \
            --function-name RegistrarHuevos \
            --zip-file fileb://lambda.zip
            
      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name RegistrarHuevos \
            --environment "Variables={STAGE=main,NODE_ENV=production,DEPLOYMENT_BRANCH=${GITHUB_REF##*/},DEPLOYMENT_TIMESTAMP=$(date +%s)}"
